services:
  postgres-product:
    image: postgres:17.4
    container_name: postgres-product
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: product
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
       - pgdata:/var/lib/postgresql/data
       - ./product-init-scripts:/docker-entrypoint-initdb.d
    ports:
       - "5432:5432"
    networks:
      - mynet
  
  postgres-inventory:
    image: postgres:17.4
    container_name: postgres-inventory
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: inventory
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
       - pgdata1:/var/lib/postgresql/data
       - ./inventory-init-scripts:/docker-entrypoint-initdb.d
    ports:
       - "6432:5432"
    networks:
      - mynet

  postgres-oms:
    image: postgres:17.4
    container_name: postgres-oms
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: oms
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
       - pgdata2:/var/lib/postgresql/data
       - ./oms-init-scripts:/docker-entrypoint-initdb.d
    ports:
       - "7432:5432"
    networks:
      - mynet
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  product:
    depends_on:
      postgres-product:
        condition: service_healthy
    build:
      context: ./product
      dockerfile: Dockerfile.multistage
    container_name: product
    hostname: product
    networks:
      - mynet
    environment:
      PORT: :8081
    ports:
      - 8081:8081
    deploy:
      restart_policy:
        condition: on-failure
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  inventory:
    depends_on:
      postgres-inventory:
        condition: service_healthy
    build:
      context: ./inventory
      dockerfile: Dockerfile.multistage
    container_name: inventory
    hostname: inventory
    networks:
      - mynet
    environment:
      PORT: :9081
    ports:
      - 9081:9081
    deploy:
      restart_policy:
        condition: on-failure
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  oms:
    depends_on:
      postgres-oms:
        condition: service_healthy
    build:
      context: ./oms
      dockerfile: Dockerfile.multistage
    container_name: oms
    hostname: oms
    networks:
      - mynet
    environment:
      PORT: :10081
    ports:
      - 10081:10081
    deploy:
      restart_policy:
        condition: on-failure
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - mynet
    depends_on:
      - product
    environment:
      - REACT_APP_API_URL_PRODUCT=http://localhost:8081
      - REACT_APP_API_URL_OMS=http://localhost:10081
networks:
  mynet:
    driver: bridge

volumes:
  pgdata:
  pgdata1:
  pgdata2: